// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  eventsIberia: [
    {
      type: 'category',
      label: 'Iberia meetups',
      link: {
        type: 'generated-index',
        title: 'MeetContent Iberia',
        description: 'Meetups in Spain and Portugal',
        slug: '/iberia',
        keywords: ['iberia'],
      },
      items: [{ type: 'autogenerated', dirName: 'iberia' }],
    },
  ],
  eventsKrakow: [
    {
      type: 'category',
      label: 'Kraków meetups',
      link: {
        type: 'generated-index',
        title: 'MeetContent Kraków',
        description: 'Meetups in Kraków',
        slug: '/krakow',
        keywords: ['krakow'],
      },
      items: [{ type: 'autogenerated', dirName: 'krakow' }],
    },
  ],
  eventsWroclaw: [
    {
      type: 'category',
      label: 'Wrocław meetups',
      link: {
        type: 'generated-index',
        title: 'MeetContent Wrocław',
        description: 'Meetups in Wrocław',
        slug: '/wroclaw',
        keywords: ['wroclaw'],
      },
      items: [{ type: 'autogenerated', dirName: 'wroclaw' }],
    },
  ],
};

module.exports = sidebars;
